#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2025 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.1.2
# Product:       sfa3x
# Model-Version: 1.1.0
#

import argparse
import time
from sensirion_i2c_driver import I2cConnection, CrcCalculator
from sensirion_shdlc_driver import ShdlcSerialPort, ShdlcConnection
from sensirion_shdlc_sensorbridge import (SensorBridgePort,
                                          SensorBridgeShdlcDevice,
                                          SensorBridgeI2cProxy)
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_sfa3x.device import Sfa3xDevice

parser = argparse.ArgumentParser()
parser.add_argument('--serial-port', '-p', default='COM1')
args = parser.parse_args()

with ShdlcSerialPort(port=args.serial_port, baudrate=460800) as port:
    bridge = SensorBridgeShdlcDevice(ShdlcConnection(port), slave_address=0)
    bridge.set_i2c_frequency(SensorBridgePort.ONE, frequency=100e3)
    bridge.set_supply_voltage(SensorBridgePort.ONE, voltage=3.3)
    bridge.switch_supply_on(SensorBridgePort.ONE)
    i2c_transceiver = SensorBridgeI2cProxy(bridge, port=SensorBridgePort.ONE)
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x5D,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Sfa3xDevice(channel)
    sensor.device_reset()
    time.sleep(1.0)
    device_marking = sensor.get_device_marking()
    print(f"device_marking: {device_marking}; "
          )
    sensor.start_continuous_measurement()
    for i in range(50):
        try:
            time.sleep(1.0)
            (hcho, humidity, temperature
             ) = sensor.read_measured_values()
            print(f"hcho: {hcho}; "
                  f"humidity: {humidity}; "
                  f"temperature: {temperature}; "
                  )
        except BaseException:
            continue
    sensor.stop_measurement()
